version: '3.8' # Or a version compatible with your Docker Compose installation

services:
  # PostgreSQL Database Service
  db:
    # Use either the official image or your custom one:
    image: lilhast1/bazaarbaza:v1.0 
    # image: your_dockerhub_username/your_db_image_name:your_tag # Or your custom image from Docker Hub
    container_name: postgres-db-standalone # A descriptive name
    environment:
      # These configure the DB initialization if using the official image and the volume is empty
      # May or may not be needed/used if using your custom image, depending on how it's built.
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: buzabuzabuza # Consider using .env file for secrets!
    volumes:
      # Persist data using a named volume. Assumes standard data path.
      - postgres_data:/var/lib/postgresql/data
    ports:
      # --- IMPORTANT ---
      # Map host port 5433 to container port 5432.
      # Your *local* .NET app will connect to localhost:5433
      - "5432:5432"
    restart: unless-stopped
    # Optional: Healthcheck is still useful
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Defines the named volume for data persistence
    driver: local