// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedKernel.Models;

#nullable disable

namespace bazaar.Migrations.LanguageDb
{
    [DbContext(typeof(LanguageDbContext))]
    [Migration("20250601121020_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedKernel.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("SharedKernel.Models.Language", b =>
                {
                    b.OwnsOne("SharedKernel.Models.Translation", "Translation", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.ToJson("Translation");

                            b1.WithOwner("Language")
                                .HasForeignKey("LanguageId");

                            b1.Navigation("Language");
                        });

                    b.Navigation("Translation");
                });
#pragma warning restore 612, 618
        }
    }
}
